server:
  port: 8901

spring:
  profile: dev
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/identity
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        max_fetch_depth: 3
        temp:
          use_jdbc_metadata_defaults: false
